name: Deploy
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get the tag name
        id: tagName
        uses: olegtarasov/get-tag@v2.1.2
        with:
          tagRegex: 'v(.*)'
      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/637710599739/locations/global/workloadIdentityPools/github/providers/github
          service_account: github@packets-compiler-prod.iam.gserviceaccount.com
      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            us-central1-docker.pkg.dev/packets-compiler-prod/packets/wstunnel:${{ steps.tagName.outputs.tag }}
            us-central1-docker.pkg.dev/packets-compiler-prod/packets/wstunnel:latest